// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFt4nFvYHJkew3Y_DTOaLIJQceQUokALc',
    appId: '1:317878982794:web:24b96289e06b222bb6b573',
    messagingSenderId: '317878982794',
    projectId: 'flutter-1abe1',
    authDomain: 'flutter-1abe1.firebaseapp.com',
    databaseURL: 'https://flutter-1abe1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1abe1.appspot.com',
    measurementId: 'G-GKWTM1CZN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcBG0G3WdmnaC0Ht9J-1IKyrJRg4iv7sU',
    appId: '1:317878982794:android:ed1c90ac73d474aeb6b573',
    messagingSenderId: '317878982794',
    projectId: 'flutter-1abe1',
    databaseURL: 'https://flutter-1abe1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1abe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKntEF97LiqY42vH1EEJbcN9eyJlAQICw',
    appId: '1:317878982794:ios:657ec7591a48cab6b6b573',
    messagingSenderId: '317878982794',
    projectId: 'flutter-1abe1',
    databaseURL: 'https://flutter-1abe1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1abe1.appspot.com',
    iosClientId: '317878982794-89cba15ssna91i2u4pjn9iauu79mhqtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hourTracker',
  );
}
